import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, {useState} from 'react'
import prisma from '../lib/prisma';




export async function getStaticProps() {
  const message = await prisma.message.findMany();
  // const stringifiedData = safeJsonStringify(message);
  // const data = JSON.parse(stringifiedData);
  return {
    props: {
      initMsg:message
    },
    revalidate: 10, 
  }
};

export default function Home({initMsg}) {
  const [messages, setMessages] = useState(initMsg)
  console.log(messages)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    {
      messages.map( (msg,index) => {
        return (
<ul key = {index}>
<li>Name: {msg.fullname}</li>
<li>Title: {msg.title}</li>
<li>Subject: {msg.subject}</li>
<li>Content: {msg.content}</li>
</ul> 
        )
      })
    }
     </main>
    </div>
  )
}

{/* */}